name = "hot100"
main = "src/index.ts"
compatibility_date = "2025-04-01"
routes = [
    { pattern = "hot100.pdv.dev", custom_domain = true }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hot100-db"
database_id = "ae7a1385-9c1b-46d8-977b-a9a2a180eadf"
