name = "hot100"
main = "src/server/index.ts"
compatibility_date = "2025-04-01"
compatability_flags = ["nodejs_compat"]
routes = [
    { pattern = "hot100.pdv.dev", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[build]
command = "esbuild src/client/index.tsx --bundle --splitting --format=esm --platform=browser --outdir=public/dist --define:process.env.NODE_ENV=\\\"production\\\""

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "hot100-db"
database_id = "ae7a1385-9c1b-46d8-977b-a9a2a180eadf"
